version: '3.7'

services:
  authentication:
    container_name: authentication
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - container_frontend
networks:
  container_frontend:
    external: true