version: '3.7'

services:
  authentication:
    container_name: authentication
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    external_links:
      - server
    networks:
      - frontend
networks:
  frontend:
    driver: bridge